version: '3.8'
services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb-container
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db

  nodejs:
    build:
      context: ../personal-blog-server
    container_name: personal-blog-server-container
    restart: always
    environment:
      - MONGO_URL=mongodb://admin:password@mongodb-container:27017/testdb?authSource=admin
    ports:
      - '3001:3001'
    depends_on:
      - mongodb

  personal-blog:
    build:
      context: ../personal-blog
    container_name: personal-blog-container
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - nodejs

volumes:
  mongodb_data:
